package sockets

import (
	"net/http"

	"github.com/gorilla/websocket"
)

var upgrader = websocket.Upgrader{}

func StockfishSocketHandler(w http.ResponseWriter, r *http.Request) {
	conn, err := upgrader.Upgrade(w, r, nil)

	if err != nil  {
		return
	}

	for {
		messageType, contents, err := conn.ReadMessage()
		if err != nil {
			return
		}

		// interface with stockfish here
		// 
		// 
		
		// send back move generated by stockfish
		if err := conn.WriteMessage(messageType, contents); err != nil {
			return
		}
	}
}